### ISSUE TITLE
Add --target=pbc.

### ISSUE THREAD

**Issue by pmichaud** [perl6/nqp#139]
This is a carryover from issue #76, which switched NQP to be able to use Parrot's PackfileView API.

Once Parrot switches from EvalPMC to PackfileView, we can create a --target=pbc option that directly creates .pbc files instead of having to go through an intermediate --target=pir step.  I'll gladly write the patches for this issue.. just wanted a placeholder ticket so that I can properly close #76.

Pm

**Comment by pmurias** [comment]
wontfix until Parrot resurfaces
