### ISSUE TITLE
parallel build fails

### ISSUE THREAD

**Issue by Rotwang** [perl6/nqp#152]
Hi,

```
$ make -v
GNU Make 3.82
Built for x86_64-unknown-linux-gnu
[...]
$ perl ./Configure.pl
[...]
$ make -j5
[...]
make[1]: *** read jobs pipe: Is a directory.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[2]: Entering directory `/ringdingding/nqp-2013.11.orig/3rdparty/dyncall/dyncall'
gcc -O3 -fPIC   -c dyncall_vector.c -o dyncall_vector.o
make[2]: *** read jobs pipe: Is a directory.  Stop.
make[2]: *** Waiting for unfinished jobs....
[...]
make[1]: *** [dyncall] Error 2
```

On linux with gnu make, parallel build will fail due to two reasons:

1) Inside nqp's main makefile three libraries have the same make recursive jump. Which means that more than one make instance (separate processes)  will try to build the same objects.
2) dyncall makefiles fail due to: http://lists.gnu.org/archive/html/bug-make/2013-12/msg00019.html

patch (agains nqp 2013.11) that should fix this issue: https://gist.github.com/Rotwang/8125363

**Comment by MasterDuke17** [comment]
Parallel building has worked since at least 2016, closing this issue.
