### ISSUE TITLE
$PREFIX/languages not acceptable for downstream packages

### ISSUE THREAD

**Issue by pstumpf** [perl6/nqp#154]
Right now, NQP and Rakudo install JVM and MoarVM bytecode under $PREFIX/languages.  This does not conform to FHS and is probably not acceptable by most distributions (definitely not on OpenBSD, at least).  The location should be changed to something under lib/ or share/.

**Comment by coke** [comment]
Working on generating a macport, which also complains about the top level "langauges/"

**Comment by moritz** [comment]
works on JVM and MoarVM in the install-dir-layout branches (rakudo + nqp). Panda works too.

It might break nqp-p though.

**Comment by FROGGS** [comment]
Shall we merge it now?

**Comment by moritz** [comment]
merged.
