### ISSUE TITLE
parrot CallContext reuse SEGV introduced by rakudo 9515bb7

### ISSUE THREAD

**Issue by rurban** [perl6/nqp#176]
We had to replace 
`proto infix:<===>(Mu $?, Mu $?) is pure { * }`
by
`proto infix:<===>($?, $?) is pure { * }`
in rakudo to fix SEGV's probably caused by an invalid CallContext in `Parrot_pcc_reuse_continuation()`.

I suspect a 6model bug.

Stacktraces:
https://gist.github.com/FROGGS/6a3d23f0b93db0a9938b

repro with the `parrot-ccreuse` branch in my rakudo fork: https://github.com/rurban/rakudo/tree/parrot-ccreuse

**Comment by pmurias** [comment]
wontfix until Parrot resurfaces
