### ISSUE TITLE
report patch to upstream libtommath

### ISSUE THREAD

**Issue by FROGGS** [perl6/nqp#192]
This should go to upstream, so it will be on system's libtommath eventually.

https://github.com/perl6/nqp/commit/bee86c99735cf5c6da852ebcaa9dcdd9099bc54b

**Comment by baby-gnu** [comment]
Patch is applied upstream, this one could be closed.

Regards.

**Comment by FROGGS** [comment]
It is still not in master yet though: https://github.com/libtom/libtommath/compare/master...develop

**Comment by flussence** [comment]
If anyone else is interested, it looks like upstream may have a pulse after all: libtom/libtommath#35

**Comment by ugexe** [comment]
The PR has is in master now, so this should be resolved
