### ISSUE TITLE
Either a NQP or PGE object mark misses a ptr for the GC

### ISSUE THREAD

**Issue by duzy** [perl6/nqp#195]
I guess this issue is about SixModelObject mark (https://github.com/parrot/parrot/issues/1108). It could be easily reproduced on low RAM.

```
Parrot_SixModelObject_mark (interp=0x611050, _self=PMC<SixModelObject> = {...}) at sixmodelobject.c:731
```

**Comment by pmurias** [comment]
wontfix until Parrot resurfaces
