### ISSUE TITLE
docs/op.markdown  some const is invalid in MoarVM

### ISSUE THREAD

**Issue by songzan** [perl6/nqp#211]
Following code is error:

say(nqp::const::TYPE_CHECK_CACHE_DEFINITIVE);
say(nqp::const::TYPE_CHECK_CACHE_THEN_METHOD);
say(nqp::const::TYPE_CHECK_NEEDS_ACCEPTS);

These Constant only valid in JVM.

Following Constant should added:

ok( (nqp::const::SIG_INT                 == 1), 'nqp::const::SIG_INT == 1');
ok( (nqp::const::SIG_BREAK               == 2), 'nqp::const::SIG_BREAK == 2');
ok( (nqp::const::SIG_HUP                 == 3), 'nqp::const::SIG_HUP == 3');
ok( (nqp::const::SIG_WINCH               == 4), 'nqp::const::SIG_WINCH == 4');

**Comment by pmurias** [comment]
Added the TYPE_* constants on the JS and MoarVM backends and put in a list of signals into the docs.
