### ISSUE TITLE
*regex-name* like regex name could not use in negative subrule

### ISSUE THREAD

**Issue by songzan** [perl6/nqp#212]
nqp-m: token token-name { <[ab]> }; ok( 'ccc' ~~ /^ <- token-name>+ $/);
     <camelia> nqp-moarvm: OUTPUT«Cannot find method 'name'␤ ...…

**Comment by pmurias** [comment]
Fixed by 5848638c16cabe9d2e4ae288bd23796b103ea9ea.

**Comment by pmurias** [comment]
Tested.
