### ISSUE TITLE
make interpreter Deep loop with negative defined class

### ISSUE THREAD

**Issue by songzan** [perl6/nqp#213]
grammar ABC {
        token user_defined_subrule { <[ab]> };
        token negative_user_defined_subrule { ^ <!user_defined_subrule>+ $}
    }

    ok( ABC.parse('ccc', :rule<negative_user_defined_subrule>) );

**Comment by jnthn** [comment]
The ! does not negate the character class, but it instead means a zero width assertion. Thus you're quantifying something that will never make progress, so it's going to be an infinite loop. Probably you wanted <-user_defined_subrule>+.
