### ISSUE TITLE
moar: not working for a tiny trivial 'foo' language

### ISSUE THREAD

**Issue by duzy** [perl6/nqp#217]
Considering this trivial 'Foo' compiler:

```
use NQPHLL;

grammar Foo::Grammar is HLL::Grammar {
    token TOP { .* }
}

class Foo::Actions is HLL::Actions {
    method TOP($/) {
        make QAST::CompUnit.new( QAST::Block.new( QAST::Stmts.new(
            QAST::Op.new( :op<say>, QAST::SVal.new( :value('foo') ) )
        ) ) );
    }
}

sub MAIN(@ARGS) {
    my $comp := HLL::Compiler.new();
    $comp.language('foo');
    $comp.parsegrammar(Foo::Grammar);
    $comp.parseactions(Foo::Actions);
    $comp.command_line(@ARGS, :encoding('utf8'), :transcode('ascii iso-8859-1'));
}
```

Doing this:
```
nqp-m --target=mbc --output=foo.mbc foo.nqp
moar \
    --libpath=$HOME/tools/perl6/nqp/install/languages/nqp/lib \
    foo.mbc \
    anything.foo
```

And it got these:
```
Too many positionals passed; expected 0 arguments but got 1
   at <unknown>:1  (<ephemeral file>::0)
 from gen/moar/stage2/NQPHLL.nqp:1244  (.../perl6/nqp/install/languages/nqp/lib/NQPHLL.moarvm:eval:172)
 from gen/moar/stage2/NQPHLL.nqp:1437  (.../perl6/nqp/install/languages/nqp/lib/NQPHLL.moarvm:evalfiles:91)
 from gen/moar/stage2/NQPHLL.nqp:1340  (.../perl6/nqp/install/languages/nqp/lib/NQPHLL.moarvm:command_eval:211)
 from gen/moar/stage2/NQPHLL.nqp:1315  (.../perl6/nqp/install/languages/nqp/lib/NQPHLL.moarvm:command_line:116)
 from foo.nqp:20  (foo.mbc:MAIN:43)
 from foo.nqp:7  (foo.mbc:<mainline>:38)
 from <unknown>:1  (foo.mbc:<main>:8)
 from <unknown>:1  (foo.mbc:<entry>:9)
```

**Comment by moritz** [comment]
Running the code without precompilation gives a better error message:

    This representation (P6str) does not support positional access
       at gen/moar/stage2/NQPHLL.nqp:1301  (./NQPHLL.moarvm:command_line:5)
     from foo.nqp:20  (<ephemeral file>:MAIN:43)
     from foo.nqp:7  (<ephemeral file>:<mainline>:38)
     from gen/moar/stage2/NQPHLL.nqp:1244  (./NQPHLL.moarvm:eval:172)
     from gen/moar/stage2/NQPHLL.nqp:1437  (./NQPHLL.moarvm:evalfiles:91)
     from gen/moar/stage2/NQPHLL.nqp:1340  (./NQPHLL.moarvm:command_eval:211)
     from gen/moar/stage2/NQPHLL.nqp:1315  (./NQPHLL.moarvm:command_line:116)
     from gen/moar/stage2/NQP.nqp:4075  (nqp.moarvm:MAIN:16)
     from gen/moar/stage2/NQP.nqp:4070  (nqp.moarvm:<mainline>:337)
     from <unknown>:1  (nqp.moarvm:<main>:8)
     from <unknown>:1  (nqp.moarvm:<entry>:9)

And the backtrace points to the invocation of `command_line`. So maybe `@ARGS`
isn't really an array?

Doing an

    nqp::say(nqp::elems(@ARGS));

Produces the same error. So I guess the signature of MAIN should be
C<sub MAIN(*@ARGS)> instead.

Not sure this is a bug.

**Comment by duzy** [comment]
Looking into NQP's compiler, we have:
```
#?if parrot
# XXX FIX ME
sub MAIN(@ARGS) {
#?endif
#?if moar
# XXX FIX ME
sub MAIN(@ARGS) {
#?endif
#?if jvm
sub MAIN(*@ARGS) {
#?endif
```

So I think moar should be working with 'MAIN(@ARGS)'. I did also 'MAIN(*@ARGS)', but it didn't give the expected result.

I believe there was something planned to do with the signature.

Lots VM specific code differences are confusing, e.g. accessing element in a string:
```
# parrot ok, but moar not
$string[1]

# moar ok
nqp::substr($string, 1, 1)
```

**Comment by duzy** [comment]
Actually this is working fine with moar instead of `MAIN(@ARGS)`:
```
sub MAIN(*@ARGS) {
    say(nqp::how(@ARGS).name(@ARGS));
    say(nqp::elems(@ARGS));
    say(@ARGS[0]);
    say(@ARGS[1]);
}
```

**Comment by arnsholt** [comment]
It should work with `MAIN(*@args)`. The difference in sig between compilers already has an issue at #203.

As for the string thing, I'm surprised it works at all. Remember: Strings aren't arrays.

**Comment by duzy** [comment]
@arnsholt Thanks for the tip, I got this :). Actually `$string[1]` works indeed on Parrot. I guess it should be complained with an error by Parrot.

**Comment by pmichaud** [comment]
NQP doesn't try to impose any semantics on the underlying VM.  If Parrot (or any other VM) desires to allow strings to be subscripted, that's entirely up to Parrot.
