### ISSUE TITLE
nqp with pre-installed moar fails t/hll/06-sprintf.t 

### ISSUE THREAD

**Issue by dod38fr** [perl6/nqp#234]
Hello

On my Debian system, nqp fails this test:
```
$ ./nqp t/hll/06-sprintf.t  | grep -A 3 'not ok'
not ok 91 - simple %b with zero value
#   Actual value: 
# Expected value: 0
ok 92 - 5.2 %e
```

nqp is built with a pre-installed moar 2015.03 (a Debian package soon to be available)

moar is built with pre-installed libraries libtommath 0.42.0 (i.e. without patch mentioned in #192, which may be unrelated ...) and libatomic-ops 7.4.2

What can I do to fix this ?

All the best

**Comment by FROGGS** [comment]
IIRC this solves it: https://github.com/libtom/libtommath/commit/6907f6ca4582064f28e3a58374083ab2a4d85418

**Comment by dod38fr** [comment]
Indeed. Once I've patch libtommath, nqp builds and tests fine.

Thanks for the help
