### ISSUE TITLE
test failure on Debian/amd64: "mod_I - positive and negative" test fails

### ISSUE THREAD

**Issue by dod38fr** [perl6/nqp#269]
Hello

On Debian/sid amd64, I've attempted to build nqp 2015.12 with moarvm 2015.12, but one nqp test is failing:
```
$ prove -lv -e './nqp-m' t/nqp/60-bigint.t 
t/nqp/60-bigint.t .. 
1..80
ok 1 - can round-trip negative number (string)
[snip]
ok 34 - mod_I - both positive
ok 35 - mod_I - negative and positive
ok 36 - mod_I - negative and positive
ok 37 - mod_I - both negative
ok 38 - mod_I - positive and negative
not ok 39 - mod_I - positive and negative
ok 40 - Bit ops (RT 109740)
ok 41 - can box to a complex type with a P6bigint target
[snip]
```

This looks like another libtommath issue (Debian's version is lagging behind the version used by nqp).

Do you know how to fix this with a patch like issue #234 ?

All the best

**Comment by FROGGS** [comment]
I guess it is this one here: https://github.com/libtom/libtommath/commit/265651b2c7e7800c8e8d257057d4494d78bded95

**Comment by dod38fr** [comment]
@FROGGS : thanks. I'll try this patch once soon.

**Comment by dod38fr** [comment]
@FROGGS : ok nqp 2015.12 builds fine on Debian with the above patch applied to libtommath

**Comment by FROGGS** [comment]
\o/
