### ISSUE TITLE
NQP parse error not caught until runtime

### ISSUE THREAD

**Issue by tbrowder** [perl6/nqp#297]
Writing "npq::die('some string');" does not result in an exception until runtime when results in an unknown P6Opaque object error.

**Comment by tbrowder** [comment]
The "npq::" is a typographical error I make in an nqp program that is only caught at run time, not at build time as I expect.

**Comment by lizmat** [comment]
> On 17 Jul 2016, at 22:33, Tom Browder <notifications@github.com> wrote:
> 
> The "npq::" is a typographical error I make in an nqp program that is only caught at run time, not at build time as I expect.

I’m afraid that’s just the way it is.  Compare this with:

$ 6 'foo::bar'
Could not find symbol '&bar'
  in block <unit> at -e line 1

At compile time it cannot be known whether we’re not going to have a “foo”.  Or can we?



Liz

**Comment by tbrowder** [comment]
I learned the issue is a consequence of namespace lookup and can't be helped.

**Comment by moritz** [comment]
For the record, here is a bit of discussion around this issue: http://irclog.perlgeek.de/perl6/2016-07-17#i_12857051
