### ISSUE TITLE
Bug in || on Moar

### ISSUE THREAD

**Issue by pmurias** [perl6/nqp#332]
```
my $bar := 4;
my int $foo2 := $bar || 200;
say($foo2);
```

Prints out 0 should print out 4.

**Comment by jeffythedragonslayer** [comment]
In 2017.01 fails to compile with "Cannot bind to natively typed variable '$foo2'; use assignment instead"

**Comment by zoffixznet** [comment]
> In 2017.01 fails to compile with "Cannot bind to natively typed variable '$foo2'; use assignment instead"

That's because you ran it in Perl 6, but one can also run code in NQP and there such a bind is allowed.

**Comment by jeffythedragonslayer** [comment]
> > That's because you ran it in Perl 6, but one can also run code in NQP and there such a bind is allowed.

Ah, I see.  Didn't realize what NQP was.

**Comment by jeffythedragonslayer** [comment]
I can reproduce this running the 'nqp' exectuable

**Comment by W4anD0eR96** [comment]
I reproduce it using code snip below:
```
my $bar := 4;
say($bar);
my int $foo := $bar || 200;
say($foo);
```

then I dump MAST and QAST, it seems QAST is correct but MAST is wrong, I don't know where to hack next, `src/vm/moar/NQP/Ops.nqp`?

**Comment by W4anD0eR96** [comment]
I try use `int = Int || 200`, `int = 4 || 200`, `Int = int || 200` and so on, all of them are ok.

The problem is we generate code like 
```
     annotation: main.nqp:3
00026      set          loc_8_obj, loc_1_obj
00027      decont       loc_10_obj, loc_1_obj
00028      if_o         loc_10_obj, label_2(00031)
00029      const_i64_16 loc_6_int, 200
00030      set          loc_7_int, loc_6_int
     label_2:
00031      set          loc_2_int, loc_7_int
```
we assume that native int value is in loc_7_int, I try to find how code generates like that but fails because I don't know how to print debug log. I mean, "say($sth.dump())" cannot print anything in bytecode

**Comment by pmurias** [comment]
Fixed it
