### ISSUE TITLE
file: docs/nqp-overview.txt contains outdated info

### ISSUE THREAD

**Issue by tbrowder** [perl6/nqp#393]
The file docs/nqp-overview.txt contains several errors regarding nqp directory structure:

+ two directories are listed that are obsolete (“src/cheats” and “src/Regex”) but no longer exist

+ directory “t/settings” is listed but no longer exists

**Comment by jnthn** [comment]
I've at least somewhat improved things in bfa15cca62.

**Comment by tbrowder** [comment]
Thanks, @jnthn! Closed by commit bfa15cc.
