### ISSUE TITLE
QAST dump methods need to sort annotation dumps

### ISSUE THREAD

**Issue by zoffixznet** [perl6/nqp#439]
We added hash randomization on MoarVM recently and now the [`QAST::Node.dump_annotations`](https://github.com/perl6/nqp/blob/1f0ecc32503dfabe41d1bb282700196156ab31b7/src/QAST/Node.nqp#L157-L177) (and—haven't checked, but—possibly [`.dump`](https://github.com/perl6/nqp/blob/1f0ecc32503dfabe41d1bb282700196156ab31b7/src/QAST/Node.nqp#L134-L155) and [node](https://github.com/perl6/nqp/tree/1f0ecc32503dfabe41d1bb282700196156ab31b7/src/QAST)-specific dump methods (IIRC they're called `.dump_extra` or something) need to sort the dumped annotations.

Otherwise, it's a bit harder to compare the two dumps side-by-side as what at first looks like a difference between a QAST dump, is just a difference in sort order.

**Comment by mryan** [comment]
I recently did some work to make QAST dumps easier to read (arguably).  I noticed in passing that the extra nodes in QAST::VM      are now listed in different order between runs - but only QAST::VM.   I'll have a closer look.

**Comment by MasterDuke17** [comment]
@niner you recently did some work to sort things. I think that was mostly for serializing bytecode or something like that, but would it have also addressed this? Fwiw, it does look like this may be fixed on HEAD https://github.com/perl6/nqp/blob/master/src/QAST/Node.nqp#L161

**Comment by zoffixznet** [comment]
> this may be fixed on HEAD 

That does indeed fix it for nodes that don't override the dumping method

> but only QAST::VM

And in QAST::VM we can see that it does override it, and the sorting fix isn't applied: https://github.com/perl6/nqp/blob/master/src/QAST/VM.nqp#L21 (need to check other nodes too)
