### ISSUE TITLE
Profiles missing some GCs

### ISSUE THREAD

**Issue by MasterDuke17** [perl6/nqp#440]
Profiles with a small number of GCs (only tested with 1 or 2 so far) have elements of the `gcs` array  where their `sequence` is -1 (not sure if it's all cases). The HTML profile template indexes into an array based on `sequence` and apparently JavaScript doesn't understand -1 as an array index, so it just uses the '-1' named attribute of the array. [Here](https://github.com/perl6/nqp/blob/master/src/vm/moar/profiler/template.html#L755-L779) `data.sequence` can be -1, so then `gcTimings` doesn't actually get any elements added.

I tried adding some `fprintf`s of `gc_seq_number` [here](https://github.com/MoarVM/MoarVM/blob/master/src/profiler/log.c#L298) and [here](https://github.com/MoarVM/MoarVM/blob/master/src/gc/orchestrate.c#L444) and it started at 0 and went up, so I don't know where the -1 is coming from. It shows up in HTML, JSON, and SQL profiles.

I was testing with code like this: `perl6 --profile -e 'use nqp; nqp::force_gc(); say "hi"; nqp::force_gc();'`

**Comment by timo** [comment]
fixed in moarvm/moarvm@eefd9a436

thanks for finding the bug :)
