### ISSUE TITLE
Cherry pick rakudo speed up

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/nqp#459]
https://github.com/rakudo/rakudo/commit/0dc4f7318f6a3a7fb525efc555409c0ac1cbe9d8
https://github.com/rakudo/rakudo/commit/5ec4a5ab449cb0bab3e3f9326a240a9150fa9aec

Thus it seems reasonable to replace `+@` with `nqp::elems`.
The problem remained is where is the NQP benchmark? Or I just do this replacement but believe it does speed up.

**Comment by zoffixznet** [comment]
Pretty sure it was already done around the same time https://github.com/rakudo/rakudo/commit/0dc4f7318f6a3a7fb525efc555409c0ac1cbe9d8 was done.

Not all nodes support `nqp::elems`, so you can't just stick it everywhere.

**Comment by pmichaud** [comment]
FWIW, another alternative might be to figure out a way to get ```+@``` to be as fast as (or a synonym for) ```nqp::elems``` when it makes sense to do so.

**Comment by W4anD0eR96** [comment]
@pmichaud I'd like to. However, I know little about our optimizer/optimize logic, wish I learn more about that the next time :-)

**Comment by W4anD0eR96** [comment]
Thanks to @MasterDuke17 https://github.com/perl6/nqp/commit/efb316e5504ec6da5653b5d7bc27a85801b362c1 for achieve it as an optimization.
