### ISSUE TITLE
Replace manual code with nqpop

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/nqp#460]
https://github.com/perl6/nqp/blob/d743c0f88d2e748bf91caf3813152bd7601b6627/src/NQP/Actions.nqp#L1629-L1636

`nqp::const::CONTROL_*` has implemented. Can we somehow replace these codes with `nqp::const::CONTROL_RETURN` ?

**Comment by W4anD0eR96** [comment]
Sorry but the problem is I don't know how to use `nqp::const::CONTROL_RETURN` :P

**Comment by zoffixznet** [comment]
Based on output of `nqp --target=optimize -e 'nqp::const::CONTROL_RETURN'`, it'll be:

```
QAST::Op.new: :op<const>, :name<CONTROL_RETURN>
```

And evaling that QAST confirms it's 32:

```
m: use QAST:from<NQP>; BEGIN $*W.compile_time_evaluate: $, QAST::Op.new: :op<call>, :name<&say>, QAST::Op.new: :op<const>, :name<CONTROL_RETURN>
rakudo-moar 148d7c56a: OUTPUT: «32␤»
```

**Comment by W4anD0eR96** [comment]
Thanks!
