### ISSUE TITLE
nqp t/nqp/114-pod-panic.t hangs

### ISSUE THREAD

**Issue by dod38fr** [perl6/nqp#467]
Hello

Debian runs non-regression tests using the binaries of an installed package. I.e. during these tests, the command `prove  -e nqp t/[chmnpqs]*` in run in freshly checked out nqp repository.

`prove` command hangs on `nqp t/nqp/114-pod-panic.t`. This script launches a nqp subprocess using `./nqp-m` . Since this test is run in a source directory without building, the `nqp-m` file is not present. Unfortunately, the test hangs in this setup.

I would expect this script to exit on error when `./nqp-,` is missing. 

See [Debian bug 900230](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900230) for more context.

All the best

**Comment by W4anD0eR96** [comment]
@jnthn  how `nqp::spawnprocasync` works on this situation?  where async proc fails and cur hanging.

**Comment by jnthn** [comment]
`nqp::procasync` calls the `error` callback, and also sends error notifications to any stdout/stderr/merge callbacks too. It seems that unlike `Proc::Async` in Rakudo, which [sets up an error callback](https://github.com/rakudo/rakudo/blob/master/src/core/Proc/Async.pm6#L318), the `run-command` in NQP [does not](https://github.com/perl6/nqp/blob/master/src/core/testing.nqp#L76).
