### ISSUE TITLE
Same code in branches

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/nqp#468]
https://github.com/perl6/nqp/blob/50bb7de4da1e90907f42fa86ee68884e79c71811/t/nqp/114-pod-panic.t#L20-L21

@tbrowder

**Comment by tbrowder** [comment]
Hm, copy-paste, good catch. At the time I was just parroting other win/*nix tests. I see no reason to keep that construct in this case.

**Comment by tbrowder** [comment]
Closed with eac?
