### ISSUE TITLE
Recur the FIXME of `get_legacy_block_list`

### ISSUE THREAD

**Issue by TisonKun** [perl6/nqp#474]
https://github.com/perl6/nqp/blob/3d13beb5f3ac7b78ab1b485f4282d8ce0670e9ba/src/NQP/World.nqp#L56-L61

Well, soon after 6 years. Let's take a look at this method. Below is the only use of it.

https://github.com/perl6/nqp/blob/3d13beb5f3ac7b78ab1b485f4282d8ce0670e9ba/src/NQP/Actions.nqp#L896-L905

So what is the design at that time?

**Comment by W4anD0eR96** [comment]
@jnthn please take a look when you are free >_<
