### ISSUE TITLE
Do we really need REPL on NQP?

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/nqp#476]
NQP is, said, used to build a compiler of Perl 6 or (fantastically) other language.

We have a lot of options like `--target=s`, `-V` for debug.

And notice that REPL on NQP is really dumb, acts far more poorly than exec a file, often print LTA error message.

It's well to be remained or (ideally) improve in the future. But as talk above, we do not aim to provide an awesome REPL on NQP and for debug, there are somewhat enough options.

I've tried to remove REPL stuff (HLL/Compiler#interactive and so on), then `nqp` acts like `perl` and no other functions break.

**Comment by zoffixznet** [comment]
> no other functions break

What about Perl 6 built on top of such nqp? Does its REPL still function?

**Comment by pmichaud** [comment]
Although NQP's REPL has much less utility in the NQP+Rakudo constellation than it once did, its real value lies when attempting to build another language or utility in NQP (e.g., that isn't Rakudo).  Having a very basic REPL available for people prototyping new language implementations is a real plus, as we found when we were testing lots of language development in the Parrot environment.

I'd definitely recommend keeping NQP's REPL around, unless it's getting in the way somehow.  I can't imagine that it takes significant resources (either software or developer time) to leave it as it is.  If the NQP REPL needs to be moved into a module or something more on-demand-ish, I can support that but it'd be really low-priority for me.

At some point there may be enough language-specific REPLs around that we can move some common features and functionality into NQP's REPL and build based on that.  But I'd want that to be use-case driven at some point in the future, and not something we spend a lot of time designing/developing/debugging now.

Pm

**Comment by jnthn** [comment]
I don't use the NQP REPL often, but it can be handy to have now and then, simple as it is. It's also a serviceable start for other languages that might be built on NQP.

> I've tried to remove REPL stuff (HLL/Compiler#interactive and so on), then nqp acts like perl and no other functions break.

Which nicely shows that it's loosely coupled and so not a maint burden, and thus costs us nearly nothing to keep.
