### ISSUE TITLE
Rework tests of HLL

### ISSUE THREAD

**Issue by TisonKun** [perl6/nqp#481]
```
t/hll/02-modules.t ..................... skipped: design changes, need re-work
t/hll/03-exports.t ..................... skipped: design changes (EXPORT now lexical), need re-work
t/hll/04-import.t ...................... skipped: design changes (EXPORT now lexical), need re-work
```

Days ago I rewrite `t/hll/01-language.t`, but fail to catch how MODULE/EXPORT/IMPORT works in NQP thus be not able to update these test with new design. I'll appreciate it if anyone does this rework or gives out tips here.

**Comment by T1S0N** [comment]
@zoffixznet any idea?

**Comment by zoffixznet** [comment]
no idea
