### ISSUE TITLE
Optimizer on int update in place

### ISSUE THREAD

**Issue by TisonKun** [perl6/nqp#496]
surprised by 5872eda8884dd8ac66d7214bf81804b41abc9d5e

why in sink context `$i++;` `++$i;` can have different code gen?

even bare `$i = $i + 3;` we don't need it's return value.

could we make a optimize strategy on this?

**Comment by zoffixznet** [comment]
Does NQP even know when the stuff is in sink context? In Rakudo, it's a [convoluted system](https://github.com/rakudo/rakudo/issues/1571).
