### ISSUE TITLE
Is NO_VALUE needed?

### ISSUE THREAD

**Issue by TisonKun** [perl6/nqp#497]
`my class NO_VALUE` defined at `src/QAST/SpecialArg.nqp`

the main usage is as `method x($n = NO_VALUE)`

we have optional args `method x($n?)` and the default value is `NQPMu`

should we continue use `NO_VALUE`? why is it so special?

**Comment by TisonKun** [comment]
FYI, the main problem might be `NQPMu` and `nqp::null()` have their own use.

The main usage of `NO_VALUE`, as mentioned above, like

```
method main($value = NO_VALUE)     { $!main := $value unless $value =:= NO_VALUE; $!main }
```

I try to refactor it as 

```
method main($value?)     { $!main := $value // $!main }
```

it would work at most situation unless `$value` become `NQPMu` or `nqp::null()`.

Semantically I would expect codes above act same.

**Comment by TisonKun** [comment]
https://github.com/perl6/nqp/blob/47271b2d2ffba982df874a347ab2dffdc24aeae7/src/NQP/Actions.nqp#L17-L32

the problem is this guy. default value to `@` is hlllist, to `%` is `hllhash`, but `$` is special. maybe a null or NQPMu. This cause concept confusion, why different?

**Comment by jnthn** [comment]
It's because setting a node property to `NQPMu`, or pretty much any other value, should work. `NO_VALUE` acts as a sentinel value, so we can never confuse it with an actual undefined value of some kind that wants to be set.
