### ISSUE TITLE
[truffle] depend on JVM backend?

### ISSUE THREAD

**Issue by TisonKun** [perl6/nqp#500]
@pmurias currently our truffle backend rely on JVM backend, I wonder if this is necessary and if not, what is the plan build NQP directly on truffle framework; if so, does it mean that truffle backend is constrained by JVM backend(both use case and performance).

To sum up, is there a draft of truffle backend design document?

Thanks for your effort!

**Comment by pmurias** [comment]
Truffle using the JVM backend is temporary.
The plan is to migrate to using just truffle when the truffle backend can
compile and run NQP itself

**Comment by TisonKun** [comment]
Sounds good.

Could you clarify the steps bootstrap NQP on truffle backend? Seems we define `TAST` and port the underneath to truffle framework. Not really sure.

Not a emergent issue but I think it helps contributor understand how truffle backend works and the stage where it finally reaches.

**Comment by pmurias** [comment]
Nqp-truffle needs to get to the point when it can compile and run the whole
NQP. Then we will compile NQP to truffle6 bytecode.
We can run the bytecode with just the BytecodeRunner part and we won't need
the JVM backend anymore.

**Comment by pmurias** [comment]
BTW. nqp-truffle is currently a bit in a state of chaos as I'm
transitioning to loading the setting
Hopefully things will get back to being a bit more sane in a few days (I'm
hoping tomorrow).

**Comment by TisonKun** [comment]
Thanks for the explanation! Close this as the issue resolved.
