### ISSUE TITLE
Role mixing is fussy

### ISSUE THREAD

**Issue by cognominal** [perl6/nqp#509]
## Context
See also https://github.com/rakudo/rakudo/issues/2404

## The code

```perl6
use QAST;
BEGIN $*LANG.refine_slang: 'MAIN', role {},
  role {
      method dotty($/) {
         say($/);

      }
  };
QAST::IVal.new(:value(666));
```

## generated error

Cannot find method 'specialize' on object of type NQPClassHOW
at gen/moar/stage2/nqpmo.nqp:835  (/usr/local/share/nqp/lib/nqpmo.moarvm:compose)
from gen/moar/stage2/nqpmo.nqp:1381  (/usr/local/share/nqp/lib/nqpmo.moarvm:mixin)
from gen/moar/stage2/QRegex.nqp:1239  (/usr/local/share/nqp/lib/QRegex.moarvm:refine_slang)

## nqp version
This is nqp version 2018.09-43-gae69994b4 built on MoarVM version 2018.09-131-g1d6562bfd

**Comment by zoffixznet** [comment]
IIRC `$*LANG` is the obsoleted one and you're meant to use `$?LANG` now.

**Comment by cognominal** [comment]
Apparently there is no $?LANG in nqp:
`Cannot call method 'refine_slang' on a null object`

**Comment by cognominal** [comment]
The problem is with roles mixing in nqp.
One must pass the role by name to the mixin. Other ways are failing.
Note: The original code in the bug report was pasted from the Perl 6 version and was incorrect. Anonymous role are not supported in nqp.
I will correct the title of the bug report.
```
nqp -e 'class A {}; my $A := A.new(); role a { method hi() { say("hi")}  };  ($A.HOW.mixin($A, a)).hi;'
hi
nqp -e 'class A {}; my $A := A.new(); my $a := role a { method hi() { say("hi")}  };  ($A.HOW.mixin($A, $a)).hi;'
Cannot find method 'specialize' on object of type
...
nqp -e 'class A {}; my $A := A.new();   ($A.HOW.mixin($A, role a { method hi() { say("hi")}  } )).hi;'
Cannot find method 'specialize' on object of type 
...
```

**Comment by cognominal** [comment]
One must explicitely instantiate the class btw
```
$ nqp -e 'class A {};   (A.HOW.mixin(A, role a { method hi() { say("hi")}  } )).hi;'
Cannot find method 'specialize' on object of type 
```

**Comment by cognominal** [comment]
I was confused about how mixin works.
.mixin does not mix in place but leaves the class unchanged and returns the mix.
There are probably other confusions in the previous code.
The following code works as expected both in nqp and Perl 6 printing "hi\n" twice.

  class A {};
  role role-a { method hi() { say("hi")}  };
  my $A := A.HOW.mixin(A, role-a);
  $A.hi;
  my $a := A.new;
  $a.HOW.mixin($a, role-a);
  $a.hi;

**Comment by cognominal** [comment]
Not a problem. Code was incorrect
