### ISSUE TITLE
Serialization error with INIT'd pointy block.

### ISSUE THREAD

**Issue by coke** [perl6/nqp#53]
$ cat pointy.pm
INIT {

GLOBAL::foo := -> { say(3) };

}
$ cat main.pm
use pointy;

$ nqp --target=pir pointy.pm > pointy.pir
$ nqp --target=pir main.pm > main.pir
Serialization Error: could not locate static code ref for closure ''
current instr.: 'deserialization_code' pc 40940 (src/stage2/QAST.pir:14242) (src/stage2/QAST.nqp:2183)
called from Sub '' pc 40481 (src/stage2/QAST.pir:14079) (src/stage2/QAST.nqp:2151)
called from Sub 'as_post' pc 40259 (src/stage2/QAST.pir:14003) (src/stage2/QAST.nqp:2139)
called from Sub 'as_post' pc 39956 (src/stage2/QAST.pir:13890) (src/stage2/QAST.nqp:2109)
called from Sub 'post' pc 39564 (src/stage2/QAST.pir:13710) (src/stage2/QAST.nqp:2072)
called from Sub 'post' pc 33144 (src/stage2/gen/NQPHLL.pir:12640) (src/stage2/gen/NQPHLL.pm:1487)
called from Sub '' pc 32411 (src/stage2/gen/NQPHLL.pir:12348) (src/stage2/gen/NQPHLL.pm:1437)
called from Sub 'compile' pc 32320 (src/stage2/gen/NQPHLL.pir:12308) (src/stage2/gen/NQPHLL.pm:1435)
called from Sub 'eval' pc 29254 (src/stage2/gen/NQPHLL.pir:11063) (src/stage2/gen/NQPHLL.pm:1206)
called from Sub 'evalfiles' pc 31784 (src/stage2/gen/NQPHLL.pir:12094) (src/stage2/gen/NQPHLL.pm:1419)
called from Sub 'command_eval' pc 30738 (src/stage2/gen/NQPHLL.pir:11686) (src/stage2/gen/NQPHLL.pm:1354)
called from Sub 'command_line' pc 30040 (src/stage2/gen/NQPHLL.pir:11425) (src/stage2/gen/NQPHLL.pm:1304)
called from Sub 'MAIN' pc 699 (src/stage2/gen/NQP.pir:227) (src/stage2/gen/NQP.pm:3090)
called from Sub '' pc 444 (src/stage2/gen/NQP.pir:155) (src/stage2/gen/NQP.pm:1479)

**Comment by pmurias** [comment]
wontfix until Parrot resurfaces
