### ISSUE TITLE
Build fails with MoarVM in a different prefix

### ISSUE THREAD

**Issue by niner** [perl6/nqp#544]
```
nine@sphinx:~/test/build/nqp (master=)> perl Configure.pl --backends=moar --prefix=/home/nine/test/build/install/nqp/ --with-moar=/home/nine/test/build/install/moar/bin/moar 
Found /home/nine/test/build/install/moar/bin/moar version 2019.05-11-g248e2980a, which is new enough.
Cleaning up ...
You can now use 'make' to build NQP.
After that, 'make test' will run some tests and
'make install' will install NQP.
nine@sphinx:~/test/build/nqp (master=)> make
mkdir -p -- 'gen/moar/stage1/gen'
'/usr/bin/perl' '/home/nine/test/build/nqp/tools/build/gen-cat.pl' moar src/how/Archetypes.nqp src/how/RoleToRoleApplier.nqp src/how/NQPConcreteRoleHOW.nqp src/how/RoleToClassApplier.nqp src/how/NQPCurriedRoleHOW.nqp src/how/NQPParametricRoleHOW.nqp src/how/NQPClassHOW.nqp src/how/NQPNativeHOW.nqp src/how/NQPAttribute.nqp src/how/NQPModuleHOW.nqp src/how/EXPORTHOW.nqp  > 'gen/moar/stage1/nqpmo.nqp'
'/home/nine/test/build/install/moar/bin/moar' --libpath=src/vm/moar/stage0 src/vm/moar/stage0/nqp.moarvm --bootstrap --setting=NULL --no-regex-lib --target=mbc --stable-sc=stage1 \
    --output='gen/moar/stage1/nqpmo.moarvm' 'gen/moar/stage1/nqpmo.nqp'
'/home/nine/test/build/install/moar/bin/moar' --libpath=src/vm/moar/stage0 src/vm/moar/stage0/nqp.moarvm --bootstrap --setting=NULL --no-regex-lib --target=mbc --stable-sc=stage1 \
    --output='gen/moar/stage1/ModuleLoader.moarvm' src/vm/moar/ModuleLoader.nqp
mkdir -p -- 'gen/moar/stage1/gen'
'/usr/bin/perl' '/home/nine/test/build/nqp/tools/build/gen-cat.pl' moar src/core/NativeTypes.nqp src/core/NQPRoutine.nqp src/core/NQPMu.nqp src/core/NQPCapture.nqp src/core/IO.nqp src/core/Regex.nqp src/core/Hash.nqp src/core/NQPLock.nqp src/core/testing.nqp src/core/YOUAREHERE.nqp  > 'gen/moar/stage1/NQPCORE.setting'
'/home/nine/test/build/install/moar/bin/moar' --libpath=src/vm/moar/stage0 src/vm/moar/stage0/nqp.moarvm --bootstrap --module-path=gen/moar/stage1 --setting=NULL --no-regex-lib --target=mbc --stable-sc=stage1 \
    --output='gen/moar/stage1/NQPCORE.setting.moarvm' 'gen/moar/stage1/NQPCORE.setting'
mkdir -p -- 'gen/moar/stage1/gen'
'/usr/bin/perl' '/home/nine/test/build/nqp/tools/build/gen-cat.pl' moar src/QAST/CompileTimeValue.nqp src/QAST/SpecialArg.nqp src/QAST/Children.nqp src/QAST/Node.nqp src/QAST/NodeList.nqp src/QAST/Regex.nqp src/QAST/IVal.nqp src/QAST/NVal.nqp src/QAST/SVal.nqp src/QAST/BVal.nqp src/QAST/WVal.nqp src/QAST/Want.nqp src/QAST/Var.nqp src/QAST/VarWithFallback.nqp src/QAST/ParamTypeCheck.nqp src/QAST/Op.nqp src/QAST/VM.nqp src/QAST/Stmts.nqp src/QAST/Stmt.nqp src/QAST/Block.nqp src/QAST/Unquote.nqp src/QAST/CompUnit.nqp src/QAST/InlinePlaceholder.nqp  > 'gen/moar/stage1/QASTNode.nqp'
'/home/nine/test/build/install/moar/bin/moar' --libpath=src/vm/moar/stage0 src/vm/moar/stage0/nqp.moarvm --bootstrap --module-path=gen/moar/stage1 --setting-path=gen/moar/stage1 --stable-sc=stage1 \
    --setting=NQPCORE --no-regex-lib --target=mbc \
    --output='gen/moar/stage1/QASTNode.moarvm' 'gen/moar/stage1/QASTNode.nqp'
mkdir -p -- 'gen/moar/stage1/gen'
'/usr/bin/perl' '/home/nine/test/build/nqp/tools/build/gen-cat.pl' moar src/QRegex/NFA.nqp src/QRegex/Cursor.nqp  > 'gen/moar/stage1/QRegex.nqp'
'/home/nine/test/build/install/moar/bin/moar' --libpath=src/vm/moar/stage0 src/vm/moar/stage0/nqp.moarvm --bootstrap --module-path=gen/moar/stage1 --setting-path=gen/moar/stage1 --stable-sc=stage1 \
    --setting=NQPCORE --no-regex-lib --target=mbc \
    --output='gen/moar/stage1/QRegex.moarvm' 'gen/moar/stage1/QRegex.nqp'
mkdir -p -- 'gen/moar/stage1/gen'
'/usr/bin/perl' '/home/nine/test/build/nqp/tools/build/gen-cat.pl' moar src/vm/moar/HLL/Backend.nqp src/HLL/Grammar.nqp src/HLL/Actions.nqp src/HLL/Compiler.nqp src/HLL/CommandLine.nqp src/HLL/World.nqp src/HLL/sprintf.nqp  > 'gen/moar/stage1/NQPHLL.nqp'
'/home/nine/test/build/install/moar/bin/moar' --libpath=src/vm/moar/stage0 src/vm/moar/stage0/nqp.moarvm --bootstrap --module-path=gen/moar/stage1 --setting-path=gen/moar/stage1 \
    --setting=NQPCORE --no-regex-lib --target=mbc --stable-sc=stage1 \
    --output='gen/moar/stage1/NQPHLL.moarvm' 'gen/moar/stage1/NQPHLL.nqp'
make: *** No rule to make target '/home/nine/test/build/install/nqp/share/nqp/lib/MAST/Ops.nqp', needed by 'gen/moar/stage1/MASTOps.moarvm'.  Stop.
```

**Comment by vrurg** [comment]
I wonder if it makes sense to pick up moar from `PATH` too if found there.

**Comment by niner** [comment]
On Friday, 24 May 2019 15:45:04 CEST Vadim Belman wrote:
> I wonder if it makes sense to pick up moar from `PATH` too if found there.

Using a moar that we were already pointed at by the user would be a start and 
fix the regression. Supporting $PATH might be a bonus in the future.

**Comment by vrurg** [comment]
I've made the first step in this direction already. Was considering if it makes sense to finalize or is better to unroll.

**Comment by kazcw** [comment]
I think using PATH to find dependencies could be simpler than correctly handling all the possible combinations of OS / --no-relocatable / --with-moar / --with-nqp

**Comment by vrurg** [comment]
Should be ok now.

**Comment by kazcw** [comment]
As of 2a742cd: build succeeds, but the installed `nqp` doesn't work because it looks for moar in a path defined relative to $0 (testing on Linux, where the relocatable installation mode is attempted). There's a `--no-relocatable` option, but it doesn't appear to do anything. If I patch `install-moar-runner.pl` and set `$relocatable = 0`, then I get a working installation.

**Comment by vrurg** [comment]
`--no-relocatable` currently do nothing to the script, you're right. Basically, it's all about binary and binary alone. The more I think about it now the more it looks like relocatable version is not compatible with `moar` in PATH. To many possible side effects if accidentally a wrong `moar`is chosen at run time.

Perhaps @patzim would have good thoughts on this.

**Comment by patzim** [comment]
The relocatable version is not suited for installation in different paths as @kazcw has already noted, as all the paths (moar, NQP home, Perl 6 home) are determined relative to the currently running executable path. This only makes sense when installing the tripplet (MoarVM, NQP and Rakudo) into the same folder and does not provide any benefit when the folder can't be moved anyways (as is the case when installing to `/usr` and similar).

Thus in the use case of @kazcw it makes sense to build the non relocatable version. Obviously `install-moar-runner.pl` should also take relocatability into account.

@vrurg: I originally wanted to support relocatability to be enabled on only some of MoarVM, NQP and Rakudo (e.g. non-relocatable MoarVM and NQP installed to `/usr` and a relocatable Rakudo somewhere else). But I couldn't come up with a real use case and thus ignored that.
I would only try to support two modes and not any others or mixtures:

1. relocatable with all three (MoarVM, NQP, Rakudo) installed into the same folder with nothing else in it (so installing a relocatable set into `/usr` is pointless as one will never want to move that folder anyways).
2. Non relocatable with all three (MoarVM, NQP, Rakudo) potentially into different folders, maybe also with other things in those folders (e.g. installing MoarVM into `/usr` and NQP and Rakudo into `/usr/local`)

I don't have much time this weekend, but might be to do something on Monday evening.

**Comment by vrurg** [comment]
@patzim Thanks for clarifying! You assured me that nothing else should be done to the compiling or scripts. I'd stick to the _one dir contains them all_ paradigm and do the following: the only case when `moar` is searched in the path is when no `--prefix`, or `--sdkroot`, or other path-defining option is used, nor `--gen-moar`. Basically, it'd be the case of plain `./Configure.pl` mostly. If `moar` is picked from `PATH` then prefix would be set based on executable location.

No exceptions. Similar would apply to #2919 with regard to `nqp`.

**Comment by vrurg** [comment]
Anyone welcome to try #546 prior to merging.

**Comment by kazcw** [comment]
After #546 it doesn't seem to be possible to build `nqp` when `moar` is in a different prefix, with or without the patches for `$relocatable` and `VERSION` that previously got it to work.

For reference, the configure options I've been using are: `perl ./Configure.pl --prefix=${out} --backends=moar --with-moar=${moar}/bin/moar`. The moar version I'm running is a recent master, 248e298. The two patches:
```
diff --git a/tools/templates/MOAR_REVISION b/tools/templates/MOAR_REVISION
index 3bdd3de84..45a44acea 100644
--- a/tools/templates/MOAR_REVISION
+++ b/tools/templates/MOAR_REVISION
@@ -1 +1 @@
-2019.05-11-g248e298
+2019.05
```
```
diff --git a/tools/build/install-moar-runner.pl b/tools/build/install-moar-runner.pl
index 7925d54a2..3cd95af9c 100755
--- a/tools/build/install-moar-runner.pl
+++ b/tools/build/install-moar-runner.pl
@@ -6,7 +6,7 @@ use warnings;
 use 5.008;
 use File::Spec;

-my $relocatable = 1;
+my $relocatable = 0;

 my ($destdir, $prefix, $lib_dir, $moar) = @ARGV;
 my $realpath = $destdir.$prefix;
```

The new failure is: `make: *** No rule to make target '/share/nqp/lib/MAST/Ops.nqp', needed by 'gen/moar/stage1/MASTOps.moarvm'.  Stop.`

Should I be invoking `Configure.pl` with different options after #546? I have tried omitting  --with-moar, but it doesn't seem to pick it up from my PATH; it just fails earlier when it tries to run it in the prefix directory, with: `bash: /nix/store/vzap5dr8g5baqlncvh3q5n54qi6ybnka-nqp-2019.05.25-8088c3/bin/moar: No such file or directory`.

**Comment by vrurg** [comment]
@kazcw Would it be possible for you to test it from my repo [vrurg/nqp](https://github.com/vrurg/nqp), branch `build-revamp`? This way it'd be slightly faster to test things. :)

**Comment by vrurg** [comment]
And you could ping me on IRC too.

**Comment by vrurg** [comment]
Seems to be working for me with #548 now. What else am I missing? ;)

**Comment by kazcw** [comment]
Not much :). It's now working for me, except I still need the patch for $relocatable. [Here's my build script](https://github.com/kazcw/nixies/blob/master/perl6/nqp.nix)

**Comment by patzim** [comment]
@kazcw Yes, that script still has to be changed. I might have some time tomorrow evening to look into that.

**Comment by vrurg** [comment]
Ok, I'm not messing with this anymore. Will follow if anything is needed from my side.
