### ISSUE TITLE
Suspicious Braid initialisation

### ISSUE THREAD

**Issue by cognominal** [perl6/nqp#559]
That line does not make any sense to me. Why initialising a Braid actions class attribute with a grammar instance ? It must be overriden somewhere to work.

        nqp::bindattr($new, Braid, '$!actions', $grammar);

https://github.com/perl6/nqp/blob/master/src/QRegex/Cursor.nqp#L36

**Comment by AlexDaniel** [comment]
That must've been ```$!grammar``` and not ```$!actions```, Llooks like a copy paste error to me.

Can you submit a PR with a fix?

**Comment by AlexDaniel** [comment]
Here's the commit:

https://github.com/perl6/nqp/commit/4adb29cbfcacf527e3323e9f7182a0825d26600a#diff-de01dcd080d97990e978333dcbbe3b2dR33

Basically it added a `:$grammar` param and the line was likely copy-pasted.

**Comment by lizmat** [comment]
Thanks for the PR!  @cognominal thanks for the spot!
