### ISSUE TITLE
Readme outdated, still says JDK8 when JDK9 is required

### ISSUE THREAD

**Issue by kentfredric** [perl6/nqp#571]
As of: https://github.com/perl6/nqp/commit/a81c05f488a6ee3848e6c1ca63fd496693fb5105

https://github.com/perl6/nqp/blob/a81c05f488a6ee3848e6c1ca63fd496693fb5105/tools/templates/jvm/Makefile.in#L132-L134

And especially due to: https://github.com/perl6/nqp/commit/104a5ce4d4eeaf42aeb62355b7a5124f18965187

https://github.com/perl6/nqp/blob/104a5ce4d4eeaf42aeb62355b7a5124f18965187/tools/templates/jvm/Makefile.in#L132-L134

Surely, the minimum is JDK9/1.9, not JDK8/1.8 as stated in README.pod:

https://github.com/perl6/nqp/blob/cd588c17dabd9732ca70ab05e9a2ae153e66f29e/README.pod#L35-L39

Especially as the "--release 9" parameter is completely not understood by JDK8.
```
javac: invalid flag: --release
```

**Comment by AlexDaniel** [comment]
Can you submit a PR to update it?

**Comment by AlexDaniel** [comment]
Or just update it directly. Invitation sent, you can accept it on this page https://github.com/perl6

**Comment by kentfredric** [comment]
Honestly I'd rather it was possible to keep supporting JDK8, given vendor side, we can't actually use anything newer yet. Confirming that using JDK9 is an inescapable reality is step 1 for getting this documentation changed IME.

**Comment by AlexDaniel** [comment]
@kentfredric what about using rakudo 2019.03.1? The requirement was bumped in and 2019.07 2019.07.1 only. 2019.03.1 is also a great release.

**Comment by kentfredric** [comment]
Currently my plan is to make 2019.07* available only using moarvm, and only support any/all jvm/moar for 2019.03.* and lower, at least until we can get a newer JDK in tree.

It just means our ability to provide fully-fledged and recent editions of things are hampered by the minimum JDK requirement, and end-users will not be able to use 2019.07.1 with the JVM backend at all, so users wanting a JVM backend will be stuck with 2019.03.1 

This isn't exactly a great situation, but I'm not in any position to do anything else about it ( Because getting newer JDK is much beyond the scope of things I can do, and requires vendor-wide action )

**Comment by kentfredric** [comment]
> Or just update it directly. Invitation sent, you can accept it on this page https://github.com/perl6

Invite accepted, however: 

- ERROR: Permission to perl6/nqp.git denied to kentfredric

Do I still need to do a PR :) ?

**Comment by AlexDaniel** [comment]
Fixed! Sorry!

**Comment by kentfredric** [comment]
Done, and thanks :)
