### ISSUE TITLE
[WIP] JVM build needs a couple of fixes.

### ISSUE THREAD

**Issue by vrurg** [perl6/nqp#589]
- Dependency on runtime .java files.
- configure_jars shall be moved from `NQP::Configure` in `nqp-configure` submodule to `NQP::Configure::NQP`.

This task just an anchor for WIP.

**Comment by pmurias** [comment]
The problem is that nqp-j uses  gen/jvm/sshare/runtime/nqp-runtime.jar which is copied from nqp-runtime.jar but does not depend on it. So when a java file is changed and recompiled nqp-j still uses the old runtime from before recompile.

**Comment by vrurg** [comment]
Closing via #590 and #591
