### ISSUE TITLE
fails to build on big endian (mips, powerpc and sparc)

### ISSUE THREAD

**Issue by ghedo** [perl6/nqp#63]
I currently get this when building nqp 2012.10 on mips:

```
/usr/bin/parrot --library=src/stage1 src/stage1/nqp.pbc \
	    --target=pir --output=src/stage2/gen/NQP.pir \
	    --module-path=src/stage2 --setting-path=src/stage2 src/stage2/gen/NQP.pm
make[2]: *** [src/stage2/nqp.pbc] Bus error
make[2]: Leaving directory `/build/buildd-nqp_2012.10-1-mips-P0hDD9/nqp-2012.10'
```

This may very well be a problem in Parrot, but I'm not sure.

**Comment by pstumpf** [comment]
NQP on MoarVM doesn’t seem to support BE platforms either (note that I have no idea whether this is a MoarVM or an NQP bug).  As of MoarVM-2014.12-3-g8cfefcb:

```
perl -MExtUtils::Command -e mkpath gen/moar/stage1/gen
perl tools/build/gen-cat.pl moar src/vm/moar/QAST/QASTRegexCompilerMAST.nqp  src/vm/moar/QAST/QASTOperationsMAST.nqp  src/vm/moar/QAST/QASTCompilerMAST.nqp   > 
gen/moar/stage1/QAST.nqp
/home/pascal/src/MoarVM/install/bin/moar --libpath=src/vm/moar/stage0 src/vm/moa
r/stage0/nqp.moarvm --bootstrap --module-path=gen/moar/stage1 --setting-path=gen
/moar/stage1  --setting=NQPCORE --no-regex-lib --target=mbc  --output=gen/moar/stage1/QAST.moarvm gen/moar/stage1/QAST.nqp
Only native types are currently supported/checked at line 1420, near ";\n       
 "
   at gen\moar\stage2\NQPHLL.nqp:485  (src/vm/moar/stage0/NQPHLL.moarvm:panic:10
5)
 from gen\moar\stage2\NQP.nqp:2926  (src/vm/moar/stage0/nqp.moarvm::109)
[...]
```

**Comment by colomon** [comment]
For what it's worth, this was working earlier this year.  But I can confirm that it currently also fails for me on PowerPC Linux.

**Comment by colomon** [comment]
1f4200169a228547d4fba27e44f9c41ad47a26a1 (of Rakudo, late Oct) seems to build NQP without issues on PowerPC.

**Comment by danielibnzayd** [comment]
I just got this error message attempting to build nqp on a powerpc via gentoo. 

To note is that I only got this far after editing:
/perl6-nqp-bba0461/3rdparty/dyncall/Makefile.config
to only use "-arch ppc".

**Comment by FROGGS** [comment]
@danielibnzayd You seem to try to build nqp for the parrot backend... Can you try to build it for MoarVM instead?

**Comment by danielibnzayd** [comment]
Thanks for the quick reply. 

When I try to build for MoarVM, I don't even get past the configure:
---------------------
>>> Configuring source in /Volumes/GENTOO/var/tmp/portage/dev-lang/moarvm-9999/work/moarvm-9999 ...
Welcome to MoarVM!

Updating submodules .................................... OK
Configuring native build environment ................... OK
    probing whether your compiler thinks that it is gcc  Can't compile simple gcc probe, so something is badly wrong at build/probe.pm line 92.
---------------------
Again, this is through gentoo portage; I haven't gone in yet to see if I need to tweak anything.

**Comment by danielibnzayd** [comment]
Thanks for the quick reply.
When I try to build for MoarVM, I don't even get past the configure:

            Configuring source in /Volumes/GENTOO/var/tmp/portage/dev-lang/moarvm-9999/work/moarvm-9999 ...
            Welcome to MoarVM!

            Updating submodules .................................... OK
            Configuring native build environment ................... OK
            probing whether your compiler thinks that it is gcc Can't compile simple gcc probe, so something is badly wrong at build/probe.pm line 92.

Again, this is through gentoo portage; I haven't gone in yet to see if I need to tweak anything.

**Comment by danielibnzayd** [comment]
@FROGGS I've just come back to it, and the nqp build fails....wasn't sure where to put this, here or elsewhere.

Makefile:218: recipe for target 'gen/moar/stage1/nqpmo.moarvm' failed
make: *** [gen/moar/stage1/nqpmo.moarvm] Illegal instruction

The Mac also throws up a crash dialog box; can post that here if need be?

**Comment by FROGGS** [comment]
@danielibnzayd please create a new issue, this here is marked Parrot specific.

**Comment by pmurias** [comment]
wontfix until Parrot resurfaces
