### ISSUE TITLE
Support parrot threads 

### ISSUE THREAD

**Issue by rurban** [perl6/nqp#67]
See https://github.com/parrot/parrot/issues/870

NQPLexPad needs to support the new Proxy pmc, 
and needs to check for the NQPLexPadInfo class more reliably.

In the parrot branch `rurban/gh870-pmc_class` we export now the dynpmc type information in the pmc and group header file, so nqplexpad.pmc can check for the dynpmc_class_NQPLexPadInfo type.

I haven't checked other failure cases yet, all tests pass, just new tests which use parrot threads do not.

**Comment by moritz** [comment]
What's the exact TODO item here? The title talks about threads, the body about lexpads. What's the exact relation? What's a valid way to test when/if this issue can be considered "done"?

**Comment by rurban** [comment]
Generally, all writes need to check for a Proxy PMC and create and schedule a updater function then.
All reads need to check for a Proxy PMC and follow it.

**Comment by pmurias** [comment]
wontfix until Parrot resurfaces
