### ISSUE TITLE
Do we need both cclass 'n' and 'nl'?

### ISSUE THREAD

**Issue by FROGGS** [perl6/nqp#82]
I've removed the ability to have a cclass 'nl' here:
https://github.com/perl6/nqp/commit/8fba6d4d60b0795ec926a9384cb31cd8c75b917e

jnthn pointed out that there might be a reason to a a CCLASS_NEWLINE that is treated as "\n" only, and one that matches "\r\n".

Do we need two newline cclasses? When yes, wouldn't an enumcharlist "\n" do that as well in addition to the cclass that matches "\r\n"?

**Comment by pmurias** [comment]
The newer backends don't implement this so it doesn't seem to be needed.
